### ISSUE TITLE
Ekonomiska reglementet måste uppdateras

### ISSUE THREAD

**Issue by emilhem** [dtekcth/styrdokument#2]
Det ekonomiska reglementet ligger i nuläget i ofas med de ändringar som det beslutades om på lilla invalsmötet den 6:e april.

**Comment by joakimgy** [comment]
Håller på att fixa!

**Comment by emilhem** [comment]
Fixad av @JoakimGit med commit 005e6a75d84cc45d99a01595805484a0a1e4bed0
