### ISSUE TITLE
DKock pls fix

### ISSUE THREAD

**Issue by ErikLjungdahl** [dtekcth/styrdokument#5]
Dessa punkter som beslutades på sektionsmötet 2018-02-22 på sidan 8 av 165 är inte förenliga:

• att under punkt 5 Intresseföreningar i reglementet lägga till DKock. 
• samt att under punkt 4.1 Uppdrag, val och mandatperiod i reglementet lägga till en punkt 4.1.9 DKock med följande innehåll:

Det borde istället vara:

• att under punkt 5 Intresseföreningar i reglementet lägga till DKock. 
• samt att under punkt 5.1 Uppdrag, val och mandatperiod i reglementet lägga till en punkt 5.1.11 DKock med följande innehåll:

**Comment by Hugsim** [comment]
Löst i https://github.com/dtekcth/styrdokument/commit/fed4d3fbdc00261aaf69059ac79081e49b88fc5b
