### ISSUE TITLE
Orimligt ekonomiskt reglemente

### ISSUE THREAD

**Issue by ErikLjungdahl** [dtekcth/styrdokument#6]
På sektionsmöte 2018-02-22 beslutades 
- **att** alla förekomster, i reglementet, av ordet “sektionsförening” ändras till “sektionskommitté”.

Detta borde rimligen även gälla ekonomiska reglementet.

**Comment by emilhem** [comment]
Ja, det har bara inte uppdaterats... har för mig att Karl skulle lösa det

**Comment by emilhem** [comment]
Se issue #3

**Comment by ErikLjungdahl** [comment]
Det uppdaterades 2018-04-24 så att internrepresentationen är ändrad, men "sektionsförening" har inte ändrats till "sektionskommitté”.

**Comment by emilhem** [comment]
Damn... :(

**Comment by XP64** [comment]
@Kirens
